#ifndef DATAPIPELINE_H
#define DATAPIPELINE_H

///////////////////////////////////////////////////////////////////////////////
// include API headers for all classes so that single include file is sufficient
#include "datapipeline/Exports.H"
#include "datapipeline/DataRow.H"
#include "datapipeline/Data.H"
#include "datapipeline/Validate.H"
#include "datapipeline/DataReader.H"
#include "datapipeline/DataWriter.H"
#include "datapipeline/CsvDataReader.H"
#include "datapipeline/XmlDataWriter.H"
#include "datapipeline/JsonDataWriter.H"

#endif /* DATAPIPELINE_H */